# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.taskinput = QtWidgets.QLineEdit(self.centralwidget)
        self.taskinput.setGeometry(QtCore.QRect(240, 140, 241, 41))
        self.taskinput.setStyleSheet("")
        self.taskinput.setObjectName("taskinput")
        self.addpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addpushButton.setGeometry(QtCore.QRect(510, 150, 93, 28))
        self.addpushButton.setStyleSheet("background-color: rgb(255, 87, 127);")
        self.addpushButton.setObjectName("addpushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 140, 101, 41))
        self.label.setStyleSheet("color: rgb(255, 87, 127);")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 210, 151, 22))
        self.comboBox.setStyleSheet("color: rgb(255, 85, 127)")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 200, 161, 41))
        self.label_2.setStyleSheet("color: rgb(255, 85, 127);")
        self.label_2.setObjectName("label_2")
        self.deletepushButton = QtWidgets.QPushButton(self.centralwidget)
        self.deletepushButton.setGeometry(QtCore.QRect(480, 210, 93, 28))
        self.deletepushButton.setStyleSheet("color: rgb(255, 85, 127)")
        self.deletepushButton.setObjectName("deletepushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 40, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 85, 127);")
        self.label_4.setObjectName("label_4")
        self.tasks_left = QtWidgets.QLabel(self.centralwidget)
        self.tasks_left.setGeometry(QtCore.QRect(600, 210, 141, 21))
        self.tasks_left.setStyleSheet("color: rgb(255, 85, 127);")
        self.tasks_left.setObjectName("tasks_left")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 240, 601, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addpushButton.setText(_translate("MainWindow", "Add Task"))
        self.label.setText(_translate("MainWindow", "Enter your Task:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "High"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Medium"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Low"))
        self.label_2.setText(_translate("MainWindow", "Choose your task priority:"))
        self.deletepushButton.setText(_translate("MainWindow", "Delete All"))
        self.label_4.setText(_translate("MainWindow", "Welcome to the Task Manager!"))
        self.tasks_left.setText(_translate("MainWindow", "0 Tasks Completed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
